"""
streamlit/pdf_export.py
-----------------------
PDF export utility for Auris regulatory reports.

Uses fpdf2 to generate professional PDFs with:
- Branded header (Auris logo text, report type, metadata)
- Structured body with proper text wrapping
- Paginated footer with confidentiality notice

Usage
-----
    from streamlit.pdf_export import export_report_to_pdf

    pdf_bytes = export_report_to_pdf(
        report_content="...",
        report_type="AML Summary Report",
        generated_by="Priya Sharma",
        period="Oct 2026",
    )
    st.download_button("Download PDF", pdf_bytes, "report.pdf", "application/pdf")
"""

from __future__ import annotations

import re
import textwrap
from datetime import datetime, timezone

from fpdf import FPDF  # fpdf2 package


# ---------------------------------------------------------------------------
# Colour palette (RGB)
# ---------------------------------------------------------------------------
_NAVY = (10, 25, 60)          # deep navy — header / footer bg
_WHITE = (255, 255, 255)
_ACCENT_BLUE = (0, 102, 204)  # section headings
_LIGHT_GRAY = (245, 247, 250) # alternating row bg
_MID_GRAY = (120, 130, 150)   # sub-text / footer text
_DARK_TEXT = (20, 30, 50)     # body text


# ---------------------------------------------------------------------------
# Markdown → plain-text stripper
# ---------------------------------------------------------------------------

_MD_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"#{1,6}\s+(.+)"), r"\1"),           # headings
    (re.compile(r"\*\*(.+?)\*\*"), r"\1"),            # bold
    (re.compile(r"\*(.+?)\*"), r"\1"),                # italic
    (re.compile(r"`(.+?)`"), r"\1"),                  # inline code
    (re.compile(r"```[\s\S]*?```"), ""),              # code blocks
    (re.compile(r"!\[.*?\]\(.*?\)"), ""),             # images
    (re.compile(r"\[(.+?)\]\(.+?\)"), r"\1"),         # links
    (re.compile(r"^\s*[-*+]\s+", re.MULTILINE), "• "),  # bullets
    (re.compile(r"^\s*\d+\.\s+", re.MULTILINE), ""),  # numbered lists
    (re.compile(r"\|.+\|", re.MULTILINE), ""),        # tables
    (re.compile(r"^\s*[-=]{3,}\s*$", re.MULTILINE), ""),  # horizontal rules
]


def _strip_markdown(text: str) -> str:
    """Remove common Markdown formatting and return plain text."""
    for pattern, replacement in _MD_PATTERNS:
        text = pattern.sub(replacement, text)
    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# ---------------------------------------------------------------------------
# Custom FPDF class
# ---------------------------------------------------------------------------

class _AurisPDF(FPDF):
    """FPDF subclass that adds Auris branded header and footer on every page."""

    def __init__(
        self,
        report_type: str,
        generated_by: str,
        period: str,
    ) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.report_type = report_type
        self.generated_by = generated_by
        self.period = period
        self.generated_at = datetime.now(tz=timezone.utc).strftime(
            "%d %b %Y, %H:%M UTC"
        )
        # Allow automatic page breaks with 25 mm bottom margin
        self.set_auto_page_break(auto=True, margin=25)

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------
    def header(self) -> None:
        """Render a branded navy header on every page."""
        # Navy background rectangle across full width
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, 210, 28, style="F")

        # "Auris" logotype in white bold
        self.set_font("Helvetica", style="B", size=18)
        self.set_text_color(*_WHITE)
        self.set_xy(10, 6)
        self.cell(40, 8, "⚡ Auris", ln=False)

        # Tagline
        self.set_font("Helvetica", size=8)
        self.set_text_color(180, 200, 240)
        self.set_xy(10, 15)
        self.cell(80, 5, "Compliance Copilot for Banking & NBFC Teams", ln=False)

        # Report type (right-aligned)
        self.set_font("Helvetica", style="B", size=10)
        self.set_text_color(*_WHITE)
        self.set_xy(110, 6)
        self.cell(90, 6, self.report_type, align="R", ln=True)

        # Period + generated by
        self.set_font("Helvetica", size=8)
        self.set_text_color(180, 200, 240)
        self.set_xy(110, 13)
        self.cell(90, 5, f"Period: {self.period} | By: {self.generated_by}", align="R", ln=True)

        # Thin accent line below header
        self.set_draw_color(*_ACCENT_BLUE)
        self.set_line_width(0.8)
        self.line(0, 28, 210, 28)

        # Reset cursor below header
        self.set_xy(10, 34)

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------
    def footer(self) -> None:
        """Render a confidentiality footer with page numbers."""
        self.set_y(-18)
        # Thin separator
        self.set_draw_color(*_MID_GRAY)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())

        self.set_y(-15)
        self.set_font("Helvetica", size=7)
        self.set_text_color(*_MID_GRAY)

        # Left: generated at
        self.set_x(10)
        self.cell(0, 5, f"Generated: {self.generated_at}", align="L", ln=False)

        # Centre: confidentiality notice
        self.set_x(60)
        self.cell(90, 5, "Generated by Auris  |  CONFIDENTIAL — Internal Use Only", align="C", ln=False)

        # Right: page number
        self.set_x(160)
        self.cell(40, 5, f"Page {self.page_no()} / {{nb}}", align="R")


# ---------------------------------------------------------------------------
# Public export function
# ---------------------------------------------------------------------------

def export_report_to_pdf(
    report_content: str,
    report_type: str,
    generated_by: str,
    period: str,
) -> bytes:
    """
    Generate a professional PDF report and return it as raw bytes.

    Parameters
    ----------
    report_content:
        The report body text (Markdown or plain text). Markdown will be
        stripped before rendering.
    report_type:
        Human-readable report type, e.g. ``"AML Summary Report"``.
    generated_by:
        Name of the user who triggered generation.
    period:
        Reporting period, e.g. ``"Oct 2026"`` or ``"Q2 FY27"``.

    Returns
    -------
    bytes
        Raw PDF content suitable for ``st.download_button``.
    """
    pdf = _AurisPDF(report_type=report_type, generated_by=generated_by, period=period)
    pdf.alias_nb_pages()  # enable {nb} total pages
    pdf.add_page()

    # ------------------------------------------------------------------
    # Report title block
    # ------------------------------------------------------------------
    pdf.set_font("Helvetica", style="B", size=14)
    pdf.set_text_color(*_ACCENT_BLUE)
    pdf.cell(0, 8, report_type, ln=True)

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*_MID_GRAY)
    pdf.cell(0, 5, f"Period: {period}   |   Prepared by: {generated_by}", ln=True)

    # Divider
    pdf.set_draw_color(*_ACCENT_BLUE)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y() + 2, 200, pdf.get_y() + 2)
    pdf.ln(6)

    # ------------------------------------------------------------------
    # Body — strip markdown, wrap and render line by line
    # ------------------------------------------------------------------
    plain_text = _strip_markdown(report_content)
    paragraphs = plain_text.split("\n")

    for para in paragraphs:
        para = para.strip()
        if not para:
            pdf.ln(3)
            continue

        # Section headings heuristic: ALL CAPS or ending with ":"
        if para.isupper() or (len(para) < 80 and para.endswith(":")):
            pdf.ln(2)
            pdf.set_font("Helvetica", style="B", size=10)
            pdf.set_text_color(*_ACCENT_BLUE)
            pdf.multi_cell(0, 6, para)
            pdf.set_text_color(*_DARK_TEXT)
        elif para.startswith("•"):
            # Bullet point
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(*_DARK_TEXT)
            pdf.set_x(14)
            pdf.multi_cell(186, 5.5, para)
        else:
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(*_DARK_TEXT)
            pdf.multi_cell(0, 5.5, para)

    # ------------------------------------------------------------------
    # Return as bytes
    # ------------------------------------------------------------------
    return bytes(pdf.output())
